### ISSUE TITLE
compile script with wrong syntax

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bibi21000/python-openzwave#84]
```
greetings,

I just found out that the inline if on line 4 of the compile.sh is wrong.

In bash scripting a comparisson between a argument and a string should be only 
with a '='

Current code:
[ 'u'$1 == 'uclean' ] && CLEAN=1

Correct code:
[ 'u'$1 = 'uclean' ] && CLEAN=1

Also the 'u' char is a little bit dummy.... why not do this way:

[ $1 == 'clean' ] && CLEAN=1

Please make this correction :)
```

Original issue reported on code.google.com by `santal.m...@gmail.com` on 11 Mar 2015 at 3:13

**Comment by bibi21000** [comment]
Hi,
The right syntax for string comparisaon is == : http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_07_01.html ( = is a synonym)
I prefer not using the same operator for variable comparison and attribution.

[ $1 == 'clean' ] && CLEAN=1
Also keep in mind that bash can be an a symlink on some distribution (to csh, zsh, )? As far as I remember this code was added for old arch linux. But not sure. Otherwise, it raises a "non unary operator" error or something linke this because $1 is not defined

The way to do is safely (check that $1 is defined before) : 
[ -n $1 ] && [ $1 == 'clean' ] && CLEAN=1

which I prefer to write  : 
[ 'u'$1 == 'uclean' ] && CLEAN=1

I've not seen that this modification was applied before. I let it as this script is now deprecated
