### ISSUE TITLE
double Power values for Fibaro Wall Plug and AEON DSC 08101

### ISSUE THREAD

**Issue by slawekgh** [bibi21000/python-openzwave#97]
For FWP and AEON DSC dimmer I have double Power metrics - one is ok , 2nd is always zero or a strange number , real power consumption is shown only in one of them

tested on python-openzwave 0.2.6:

for node in network.nodes:
     for value in network.nodes[node].values:
         label=network.nodes[node].values[value].label
         print "node:"+str(node)+" value:"+str(value)+" label:"+str(network.nodes[node].values[value].label)+" data:"+str(network.nodes[node].values[value].data)+" data_items:"+str(network.nodes[node].values[value].data_items)+" units:"+str(network.nodes[node].values[value].units)
 

below only part of whole listing - only with "power" metrics: 
[...]
node:3 value:72057594093256770 label:Power data:0.0 data_items:Read only units:W
node:3 value:72057594093273218 label:Power data:0.0 data_items:Read only units:W
[...]
node:4 value:72057594110050434 label:Power data:17.8999996185 data_items:Read only units:W
node:4 value:72057594110033986 label:Power data:50.2000007629 data_items:Read only units:W
[...]

in the first case (node=3, AEON DSC) real power is zero so I dont know which metric is correct and which is dummy

in 2nd case (node=4, Fibaro Wall Plug) real power consumption is 50W (my laptop), 2nd value (17.xxx W) is not true , its a kind of bogus strange number

**Comment by bibi21000** [comment]
network.nodes[4].values[72057594110050434].refresh()
first_power = network.nodes[4].values[72057594110050434].data
network.nodes[4].values[72057594110033986].refresh()
second_power = network.nodes[4].values[72057594110033986].data

I saw 2 differents valueIds 72057594110050434 and 72057594110033986 so I don't think it's a bug
Normally  power meters values are sent as 2 values : one for the instant one and one for the cumulative one. You'll find more informations in your product's documentation

Otherwise, you can ask to the openzwave project. Python-openzwave only relays notifications from c++ library
